### PR TITLE
Created UI for Notes, PYQ page

### PR DESCRIPTION
**Pull request by battuAshita**
## Description
- Created Popup dialog to add new notes, previous papers
- Added a table to display all notes, previous papers

### CODE REVIEW

**Comment by ExpressHermes** [comment]
@battuAshita Can you please add the screenshots of the UI in the PR description for reference?

**Comment by battuAshita** [comment]
> @battuAshita Can you please add the screenshots of the UI in the PR description for reference?

Yes.

**Comment by battuAshita** [comment]
notes

papers

add

**Comment by ashutosh321607** [comment]
@battuAshita in the sidebar highlights the button or page you are on, at that time. for example 
147960264-0fa81507-e714-445f-b64b-ce50a16d79e2
In this case, PYQ should be purple, and others are white, so the user knows the PYQ button is already clicked and non-clickable.

**Comment by ashutosh321607** [comment]
> notes
> 
> papers
> 
> add

as I had discussed with you to add a search bar on top of the table to filter, please do it, 
I am not seeing any button to increase or decrease vote :((

**Comment by ashutosh321607** [comment]
@battuAshita @Ananyaiitbhilai I am accepting your PR for now, but in the next PR expected work is Frontend and Backend are connected and working properly. 
After that, you can work on the issues that are mentioned above.

**Pull request merged**
